### ISSUE TITLE
__init__() got an unexpected keyword argument 'interlayers'

### ISSUE THREAD

**Issue by KishorKS** [qiuqiangkong/mir-1k_source_separation#1]
Got an error which is mentioned in the subject while running main_dnn.py.
While executing below line i am getting this error.
md = Model( in_layers=[in1], out_layers=[out_b, out_c], inter_layers=[in1, b1, c1] )
Could please help me.

**Comment by qiuqiangkong** [comment]
Hi KishorKS, the bug is fixed. You can pull the latest version of code.
